### ISSUE TITLE
[Feature UX]: Attempt to clean up hung FS on next run

### ISSUE THREAD

**Issue by edrex** [andrewosh/hyperdrive-fuse#5]
Empirically, the biggest usability issue with FUSE-based end-user storage access solutions is hangs due to FS driver exit without unmount.

This tends to happen to many users early on in testing the software, and can cause core user environment components (ie, Finder) to hang. This is like the worst case bad out of box experience.

So why not try to detect and recover from these hangs on subsequent runs? Maybe this could be a reusable module in @fuse-friends.

This feature request is a stub/placeholder for discussion as this needs a lot of work fleshing out specifics of the mechanics of recovering from these hangs.

**Comment by edrex** [comment]
sorry this is too vague, will follow up as needed with specific issues.

**Comment by andrewosh** [comment]
@edrex There's definitely an issue on OSX where attempting to unmount when the mountpoint is in use (which in practice usually happens when the Finder is open + pointing to the mountpoint during the unmount), causes major instability. 

We're still trying to find good solutions for this, because once this unstable state is reached there's little room for recovery -- all available unmount commands tend to fail.
